# Generated by Django 4.2 on 2026-06-13 02:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bolao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('valor_entrada', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor de Entrada')),
                ('premio_total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Prêmio Total')),
                ('data_inicio', models.DateTimeField(verbose_name='Data de Início')),
                ('data_fim', models.DateTimeField(verbose_name='Data de Fim')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('finalizado', models.BooleanField(default=False, verbose_name='Finalizado')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
            ],
            options={
                'verbose_name': 'Bolão',
                'verbose_name_plural': 'Bolões',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='EntradaBolao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_pago', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Pago')),
                ('data_entrada', models.DateTimeField(auto_now_add=True, verbose_name='Data de Entrada')),
            ],
            options={
                'verbose_name': 'Entrada no Bolão',
                'verbose_name_plural': 'Entradas nos Bolões',
            },
        ),
        migrations.CreateModel(
            name='Premiacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor do Prêmio')),
                ('posicao', models.IntegerField(verbose_name='Posição')),
                ('data_premiacao', models.DateTimeField(auto_now_add=True, verbose_name='Data da Premiação')),
                ('bolao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='premiacoes', to='boloes.bolao', verbose_name='Bolão')),
            ],
            options={
                'verbose_name': 'Premiação',
                'verbose_name_plural': 'Premiações',
                'ordering': ['posicao'],
            },
        ),
    ]
