# Generated by Django 4.2 on 2026-06-13 02:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('desafios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('boloes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='premiacao',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='premiacoes', to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
        migrations.AddField(
            model_name='entradabolao',
            name='bolao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entradas', to='boloes.bolao', verbose_name='Bolão'),
        ),
        migrations.AddField(
            model_name='entradabolao',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entradas_bolao', to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
        migrations.AddField(
            model_name='bolao',
            name='criador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boloes_criados', to=settings.AUTH_USER_MODEL, verbose_name='Criador'),
        ),
        migrations.AddField(
            model_name='bolao',
            name='desafio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boloes', to='desafios.desafio', verbose_name='Desafio Vinculado'),
        ),
        migrations.AlterUniqueTogether(
            name='entradabolao',
            unique_together={('usuario', 'bolao')},
        ),
    ]
