# Generated by Django 4.2 on 2026-06-13 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boloes', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bolao',
            name='regra_distribuicao',
            field=models.CharField(choices=[('TOP3', 'Top 3 (50% - 30% - 20%)'), ('WINNER', 'Só o 1º lugar (100%)')], default='TOP3', max_length=10, verbose_name='Distribuição do Prêmio'),
        ),
    ]
