# Generated by Django 4.2 on 2026-06-13 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boloes', '0003_bolao_regra_distribuicao'),
    ]

    operations = [
        migrations.AddField(
            model_name='bolao',
            name='publico',
            field=models.BooleanField(default=True, verbose_name='Público'),
        ),
    ]
