# Generated by Django 4.2 on 2026-06-13 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='onboarding_completo',
            field=models.BooleanField(default=False, verbose_name='Onboarding Completo'),
        ),
    ]
