# Generated by Django 4.2 on 2026-06-13 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_usuario_onboarding_completo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='coins',
        ),
        migrations.AddField(
            model_name='usuario',
            name='saldo_reais',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Saldo (R$)'),
        ),
    ]
