# Generated by Django 4.2 on 2026-06-13 02:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comprovacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='comprovacoes/', verbose_name='Arquivo')),
                ('link', models.URLField(blank=True, verbose_name='Link')),
                ('aprovada', models.BooleanField(blank=True, help_text='None=Pendente, True=Aprovada, False=Rejeitada', null=True, verbose_name='Aprovada')),
                ('data_envio', models.DateTimeField(auto_now_add=True, verbose_name='Data de Envio')),
            ],
            options={
                'verbose_name': 'Comprovação',
                'verbose_name_plural': 'Comprovações',
                'ordering': ['-data_envio'],
            },
        ),
        migrations.CreateModel(
            name='Desafio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('tipo', models.CharField(choices=[('DIARIO', 'Diário'), ('SEMANAL', 'Semanal'), ('MENSAL', 'Mensal'), ('CUSTOM', 'Personalizado')], max_length=10, verbose_name='Tipo')),
                ('categoria', models.CharField(choices=[('PROGRAMACAO', 'Programação'), ('DESIGN', 'Design'), ('DADOS', 'Dados'), ('DEVOPS', 'DevOps'), ('ESTUDO', 'Estudo'), ('OUTRO', 'Outro')], max_length=15, verbose_name='Categoria')),
                ('data_inicio', models.DateTimeField(verbose_name='Data de Início')),
                ('data_fim', models.DateTimeField(verbose_name='Data de Fim')),
                ('max_participantes', models.IntegerField(default=50, verbose_name='Máximo de Participantes')),
                ('xp_recompensa', models.IntegerField(default=50, verbose_name='XP de Recompensa')),
                ('coins_recompensa', models.DecimalField(decimal_places=2, default=10, max_digits=10, verbose_name='Moedas de Recompensa')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='desafios/', verbose_name='Imagem')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
            ],
            options={
                'verbose_name': 'Desafio',
                'verbose_name_plural': 'Desafios',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='Participacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_entrada', models.DateTimeField(auto_now_add=True, verbose_name='Data de Entrada')),
                ('progresso', models.IntegerField(default=0, help_text='Percentual de conclusão (0-100)', verbose_name='Progresso (%)')),
                ('concluido', models.BooleanField(default=False, verbose_name='Concluído')),
                ('desafio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participacoes', to='desafios.desafio', verbose_name='Desafio')),
            ],
            options={
                'verbose_name': 'Participação',
                'verbose_name_plural': 'Participações',
            },
        ),
    ]
