# Generated by Django 4.2 on 2026-06-13 02:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('desafios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='participacao',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participacoes', to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
        migrations.AddField(
            model_name='desafio',
            name='criador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='desafios_criados', to=settings.AUTH_USER_MODEL, verbose_name='Criador'),
        ),
        migrations.AddField(
            model_name='comprovacao',
            name='participacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comprovacoes', to='desafios.participacao', verbose_name='Participação'),
        ),
        migrations.AlterUniqueTogether(
            name='participacao',
            unique_together={('usuario', 'desafio')},
        ),
    ]
