# Generated by Django 4.2 on 2026-06-13 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desafios', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='desafio',
            name='roadmap_ia',
            field=models.JSONField(blank=True, null=True, verbose_name='Roadmap IA (Gemini)'),
        ),
    ]
