# Generated by Django 4.2 on 2026-06-13 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desafios', '0003_desafio_roadmap_ia'),
    ]

    operations = [
        migrations.AddField(
            model_name='desafio',
            name='publico',
            field=models.BooleanField(default=True, verbose_name='Público'),
        ),
    ]
