# Generated by Django 4.2 on 2026-06-13 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DesafioEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patrocinio', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor do Patrocínio')),
                ('vagas_emprego', models.BooleanField(default=False, verbose_name='Oferece Vagas de Emprego')),
                ('link_vaga', models.URLField(blank=True, verbose_name='Link da Vaga')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
            ],
            options={
                'verbose_name': 'Desafio de Empresa',
                'verbose_name_plural': 'Desafios de Empresas',
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_empresa', models.CharField(max_length=200, verbose_name='Nome da Empresa')),
                ('cnpj', models.CharField(blank=True, max_length=18, verbose_name='CNPJ')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='empresas/', verbose_name='Logo')),
                ('site', models.URLField(blank=True, verbose_name='Site')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
            },
        ),
    ]
