# Generated by Django 4.2 on 2026-06-13 02:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('desafios', '0002_initial'),
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='empresa', to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
        migrations.AddField(
            model_name='desafioempresa',
            name='desafio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empresa_patrocinadora', to='desafios.desafio', verbose_name='Desafio'),
        ),
        migrations.AddField(
            model_name='desafioempresa',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='desafios_empresa', to='empresas.empresa', verbose_name='Empresa'),
        ),
    ]
