# Generated by Django 4.2 on 2026-06-13 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='desafioempresa',
            name='duracao_dias',
            field=models.IntegerField(default=14, verbose_name='Duração do desafio (dias)'),
        ),
        migrations.AddField(
            model_name='desafioempresa',
            name='max_candidatos',
            field=models.IntegerField(default=20, verbose_name='Máx. de candidatos'),
        ),
        migrations.AddField(
            model_name='desafioempresa',
            name='metrica_consistencia',
            field=models.BooleanField(default=True, verbose_name='Consistência diária (ofensiva)'),
        ),
        migrations.AddField(
            model_name='desafioempresa',
            name='metrica_qualidade_ia',
            field=models.BooleanField(default=True, verbose_name='Qualidade de commits (IA)'),
        ),
        migrations.AddField(
            model_name='desafioempresa',
            name='metrica_score',
            field=models.BooleanField(default=False, verbose_name='Score de disciplina'),
        ),
        migrations.AddField(
            model_name='desafioempresa',
            name='metrica_tempo',
            field=models.BooleanField(default=True, verbose_name='Tempo médio de entrega'),
        ),
        migrations.AddField(
            model_name='desafioempresa',
            name='nivel_exigido',
            field=models.CharField(choices=[('Junior', 'Júnior'), ('Pleno', 'Pleno'), ('Senior', 'Sênior')], default='Pleno', max_length=20, verbose_name='Nível exigido'),
        ),
        migrations.AddField(
            model_name='desafioempresa',
            name='stack_avaliada',
            field=models.CharField(blank=True, max_length=200, verbose_name='Tecnologia / Stack avaliada'),
        ),
    ]
